apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: shuzasa/user-service:v1.0
          ports:
            - name: user-service
              containerPort: 8082
          env:
            - name: MICRO_SERVER_ADDRESS
              value: ":8082"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_USER
              value: "admin"
            - name: DB_NAME
              value: "porter_db"
            - name: DB_PASSWORD
              value: "123456"
            - name: APP_VERSION
              value: "v1.0"
            - name: MICRO_REGISTRY
              value: "kubernetes"


---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP